#pragma once

#include <initializer_list>

namespace CRMuSR2::SimCRMu {
constexpr auto defaultMacro = {
    "#############################################################################",
    "# Initialization settings",
    "#############################################################################",
    "",
    "/control/verbose 2",
    "#/control/saveHistory",
    "/run/verbose 2",
    "",
    "#/Mustard/Detector/Description/Ixport SimCRMu.yaml",
    "",
    "/run/initialize",
    "",
    "/Mustard/EcoMug/Position/HSphere 0 0 0 m",
    "/Mustard/EcoMug/Size/HSphere/Radius 4 m",
    "",
    // "/CRMuSR2/Analysis/FilePath SimCRMu_untitled",
    // "/CRMuSR2/Analysis/FileMode RECREATE",
    "",
#if MUSTARD_USE_G4VIS
    "#############################################################################",
    "# Visualization settings",
    "#############################################################################",
    "",
    "/vis/open OGL",
    "",
    "/vis/viewer/set/autoRefresh no",
    "/vis/verbose errors",
    "",
    "/vis/drawVolume",
    "",
    "/vis/viewer/set/viewpointVector -1 0.5 0.5",
    "/vis/viewer/set/lightsVector -1 1 1",
    "#/vis/viewer/set/rotationStyle freeRotation",
    "/vis/viewer/set/projection p",
    "/vis/viewer/set/style s",
    "/vis/viewer/set/auxiliaryEdge no",
    "#/vis/viewer/set/lineSegmentsPerCircle 100",
    "/vis/viewer/zoom 2.5",
    "",
    "# Visibility",
    "",
    "/vis/geometry/set/visibility World                         0          no",
    "/vis/geometry/set/visibility PDRVirtualWallBox                        0          no",
    "/vis/geometry/set/visibility PDRSiPMBox                        0          no",
    "",
    "# Colors",
    "/vis/geometry/set/colour Target                     0     1     1     1     0.8",
    "/vis/geometry/set/colour PDRSupport                 0     1     1     1     0.3",
    "/vis/geometry/set/colour PDRScintillator            0     1     1     1     0.5",
    "/vis/geometry/set/colour PDRSiPMCoupler             0     1     1     1     0.4",
    "/vis/geometry/set/colour PDRSiPMSensor              0     1     1     1     0.8",
    "",
    "/vis/scene/add/date",
    "/vis/scene/add/axes 0 0 0 1 m",
    "/vis/scene/add/trajectories smooth #rich",
    "/vis/scene/add/hits",
    "",
    "/vis/filtering/trajectories/create/particleFilter",
    "/vis/filtering/trajectories/particleFilter-0/add mu+",
    "/vis/filtering/trajectories/particleFilter-0/add mu-",
    "/vis/filtering/trajectories/particleFilter-0/add muonium",
    "/vis/filtering/trajectories/particleFilter-0/add anti_muonium",
    "/vis/filtering/trajectories/particleFilter-0/add e+",
    "/vis/filtering/trajectories/particleFilter-0/add e-",
    "/vis/filtering/trajectories/particleFilter-0/add gamma",
    "/vis/filtering/trajectories/particleFilter-0/add opticalphoton",
    "/vis/filtering/trajectories/particleFilter-0/add neutron",
    "/vis/filtering/trajectories/particleFilter-0/add anti_neutron",
    "/vis/filtering/trajectories/particleFilter-0/add proton",
    "/vis/filtering/trajectories/particleFilter-0/add anti_proton",
    "/vis/filtering/trajectories/particleFilter-0/add pi+",
    "/vis/filtering/trajectories/particleFilter-0/add pi-",
    "/vis/filtering/trajectories/particleFilter-0/add pi0",
    "",
    "/vis/modeling/trajectories/create/drawByParticleID",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts no",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSize 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsSizeType screen",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setAuxPtsType dots",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawLine yes",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts yes",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 2",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSizeType screen",
    "/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsType dots",
    "",
    "/vis/modeling/trajectories/drawByParticleID-0/setRGBA muonium 1 0 1 1",
    "/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_muonium 1 0 1 1",
    "",
    "/vis/scene/endOfEventAction accumulate",
    "",
    "/vis/verbose warnings",
    "/vis/viewer/set/autoRefresh yes",

#endif

    ""};
} // namespace CRMuSR2::SimCRMu
